### ISSUE TITLE
Linux binaries

### ISSUE THREAD

**Issue by fsuarezo** [enclave-networks/multicast-test#2]
Hi!
Do you happen to have the linux binary? In the page it says "Download for Windows and Linux" but the Linux is not to be found. And I can't compile C#.

**Comment by mkaatman** [comment]
Agreed a linux binary or some compile instructions could help.

**Comment by groupmsl** [comment]
You need Mono installed on Linux for this to work. The exe will run on both Windows and Linux.

Once you have Mono installed, it's just:
`mono multicast-test.exe`

**Comment by enclave-marc-barry** [comment]
[Latest release](https://github.com/enclave-networks/multicast-test/releases/tag/multicast-test-v1.0.1.0) includes a binary pre-compiled for `linux-x64` architecture, just download, `chmod +x` and run.
